baseurl = "https://www.felixparadis.com"
title = "Félix Paradis"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "blsfljksfiou"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

googleAnalytics = "UA-109396923-1"
[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[params]
    author = "Félix Paradis"
    hello = "Hello, I'm Félix Paradis 👋"
    info = "You can find me online at various places:"
    description = "Felix Paradis's personal blog and homepage"
    keywords = "blog,developer,tech"
    avatarurl = "images/profile.webp"
    avatarurlBackup = "images/profile.png"
    images = ["images/profile.png"] # for og:image

    # favicon_32 = "/img/favicon-32x32.png"
    # favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    # Specify colorscheme. Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    custom_css = []
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/FelDev/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 2
    url = "https://medium.com/@FelixParadis"
[[params.social]]
    name = "CodePen"
    icon = "fab fa-codepen fa-2x"
    weight = 5
    url = "https://codepen.io/FelDev/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    svg = '<svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="stack-exchange" class="svg-inline--fa fa-stack-exchange fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M17.7 332.3h412.7v22c0 37.7-29.3 68-65.3 68h-19L259.3 512v-89.7H83c-36 0-65.3-30.3-65.3-68v-22zm0-23.6h412.7v-85H17.7v85zm0-109.4h412.7v-85H17.7v85zM365 0H83C47 0 17.7 30.3 17.7 67.7V90h412.7V67.7C430.3 30.3 401 0 365 0z"></path></svg>'
    weight = 4
    url = "https://www.linkedin.com/in/felix-paradis/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 6
    url = "https://twitter.com/SirFelDev/"
[[params.social]]
    name = "Stack Exchange"
    icon = "fab fa-stack-exchange fa-2x"
    weight = 3
    url = "https://stackexchange.com/users/7861276/feldev?tab=accounts"

[languages]
    [languages.en]
        languagename = "English"
        
        # Menu links
        [languages.en.menu]

            # [[languages.en.menu.main]]
            # name = "About"
            # weight = 1
            # url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"
            
            [[languages.en.menu.main]]
            name = "Referral Links"
            weight = 2
            url = "referral-links/"

            # #TODO: include netlify contact form
            [[languages.en.menu.main]]
            name = "Contact"
            weight = 5
            url = "contact/"


    # [languages.fr-ca]
    #     languagename = "Français"
    #     title = "Félix Paradis"

    #     [languages.fr-ca.params]
    #         author = "Félix Paradis"
    #         info = "Enchanté"
    #         description = "Site personnel de Félix Paradis"
    #         keywords = "blog,code,personnel"
    #         footercontent = "Super nice."

    #     # Menu links
    #     [languages.fr-ca.menu]

    #         # [[languages.fr-ca.menu.main]]
    #         # name = "À propos"
    #         # weight = 1
    #         # url = "about/"

    #         # [[languages.fr-ca.menu.main]]
    #         # name = "Blog"
    #         # weight = 2
    #         # url = "posts/"

    #         [[languages.fr-ca.menu.main]]
    #         name = "Projets"
    #         weight = 3
    #         url = "projects/"

    #         [[languages.fr-ca.menu.main]]
    #         name = "Contact"
    #         weight = 5
    #         url = "contact/"