[build]
command = "hugo --minify"
publish = "public/"

environment = {HUGO_VERSION = "0.120.4", NODE_VERSION = "18"}

[[redirects]]
force = false
from = "/humour"
status = 301
to = "/fr/posts/repertoire-des-soirees-dhumour-a-sherbrooke"

[[redirects]]
force = false
from = "/wp-admin"
status = 301
to = "/admin"

[[redirects]]
force = false
from = "/*.php"
status = 301
to = "/admin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"