[build]
command = "hugo --minify"
publish = "public/"

[context.production.environment]
HUGO_VERSION = "0.88.1"
NODE_VERSION = "14"

[[redirects]]
force = false
from = "/wp-admin"
status = 301
to = "/admin"

[[redirects]]
force = false
from = "/*.php"
status = 301
to = "/admin"
[[redirects]]
from = "/arc-sw.js"
status = 200
to = "https://arc.io/arc-sw.js"
