[context.production.environment]
  HUGO_VERSION = "0.75.1"
  NODE_VERSION = "12"

[[redirects]]
  from = "/wp-admin"
  to = "/admin"
  status = 301
  force = false

[[redirects]]
  from = "/*.php"
  to = "/admin"
  status = 301
  force = false
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"  
  status = 200
