[build]
command = "hugo --minify"
publish = "public/"

environment = {HUGO_VERSION = "0.98.0", NODE_VERSION = "16"}

[[redirects]]
force = false
from = "/wp-admin"
status = 301
to = "/admin"

[[redirects]]
force = false
from = "/*.php"
status = 301
to = "/admin"
[[redirects]]
from = "/arc-sw.js"
status = 200
to = "https://arc.io/arc-sw.js"


[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"