[build]
  command = "hugo --minify"
  publish = "public/"

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  NODE_VERSION = "14"

[[redirects]]
  from = "/wp-admin"
  to = "/admin"
  status = 301
  force = false

[[redirects]]
  from = "/*.php"
  to = "/admin"
  status = 301
  force = false
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"  
  status = 200
