name: Trigger Netlify Build
on:
  schedule:
    - cron: "2 0 1 1 *" # January 1st, at 00:02
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
